export type Question = {
    id: number;
    text: string;
    options: string[];
    difficulty: number;
};

export type AnswerResponse = {
    correct: boolean;
    totalPoints: number;
    newLevel: number;
    isComplete: boolean;
};

export type ResultBreakdown = {
    questionId: number;
    text: string;
    correct: boolean;
    answerGiven: string;
    correctAnswer?: string;
    pointsAwarded: number;
    difficultyAtTime: number;
};

export type ResultsResponse = {
    score: number;
    accuracy: number;
    correctAnswers: number;
    totalQuestions: number;
    breakdown: ResultBreakdown[];
};

export type MeResponse = {
    id: number;
    displayName: string;
    lastQuizAt: string | null;
    isNameAutoGenerated: boolean;
    role: "User" | "Tester" | "Admin";
    canPlay: boolean;
    canManageQuestions: boolean;
    canEnterLeaderboard: boolean;
};

export type LeaderboardEntry = {
    userId: number;
    displayName: string;
    totalScore: number;
    attempts: number;
    rank: number;
};

export type StatsResponse = {
    totalAttempts: number;
    totalScore: number;
    averageScore: number;
    bestScore: number;
    averageAccuracy: number;
};
