using AdaptiveQuiz.Api.Data;
using AdaptiveQuiz.Api.Domain;
using AdaptiveQuiz.Api.Infrastructure;
using AdaptiveQuiz.Api.Requests;
using AdaptiveQuiz.Api.Responses;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace AdaptiveQuiz.Api.Services;

public class QuizService
{
    private readonly AppDbContext _context;
    const int MaxQuestions = 3;
    private static readonly string[] Adjectives =
        { "Swift", "Clever", "Brave", "Curious", "Lucky" };
    private static readonly string[] Animals =
        { "Tiger", "Fox", "Eagle", "Shark", "Wolf" };

    public QuizService(AppDbContext context)
    {
        _context = context;
    }

    private string GenerateDisplayName()
    {
        var rand = Random.Shared;

        var adj = Adjectives[rand.Next(Adjectives.Length)];
        var animal = Animals[rand.Next(Animals.Length)];
        var number = rand.Next(10, 99);

        return $"{adj}{animal}{number}";
    }

    private static bool HasMonthlyRestriction(User user)
    {
        return user.Role == Roles.User;
    }

    private static bool CanRepeatQuestions(User user)
    {
        return user.Role == Roles.Tester ||
               user.Role == Roles.Admin;
    }

    private static bool CanEnterLeaderboard(User user)
    {
        return user.Role != Roles.Admin;
    }

    public async Task<User> EnsureUserExists(string email)
{
    var user = await _context.Users
        .FirstOrDefaultAsync(u => u.Email == email);

    if (user == null)
    {
        user = new User
        {
            Email = email,
            Role = Roles.User,
            CurrentLevel = 1,
            DisplayName = GenerateDisplayName(),
            IsNameAutoGenerated = true
        };

        _context.Users.Add(user);
        await _context.SaveChangesAsync();
    }

    return user;
}

    public async Task<QuizAttempt> StartQuizForUser(string email)
    {
        var user = await EnsureUserExists(email);
        return await StartQuiz(user.Id);
    }

    public async Task<QuizAttempt> StartQuiz(int userId)
    {
        var user = await _context.Users.FindAsync(userId);

        if (user == null)
            throw new Exception("User not found");

        // Monthly restriction
        if (HasMonthlyRestriction(user) && user.LastQuizAt.HasValue)
        {
            var now = DateTime.UtcNow;
            var last = user.LastQuizAt.Value;

            if (last.Month == now.Month && last.Year == now.Year)
                throw new Exception("User has already taken quiz this month");
        }

        var attempt = new QuizAttempt
        {
            UserId = user.Id,
            StartedAt = DateTime.UtcNow,
            StartingLevel = user.CurrentLevel,
            CurrentLevel = user.CurrentLevel,
            Score = 0
        };

        _context.QuizAttempts.Add(attempt);

        user.LastQuizAt = DateTime.UtcNow;

        await _context.SaveChangesAsync();

        return attempt;
    }

    public async Task<Question> GetNextQuestion(int attemptId, int currentUserId)
    {
        var attempt = await _context.QuizAttempts
            .Include(a => a.Questions)
            .FirstOrDefaultAsync(a => a.Id == attemptId);

        if (attempt == null)
            throw new Exception("Quiz not found");

        if (attempt.UserId != currentUserId)
            throw new Exception("Unauthorized access");

        // Already completed
        if (attempt.CompletedAt != null)
            throw new Exception("Quiz already completed");

        // Reached max questions
        if (attempt.Questions.Count >= 10)
            throw new Exception("Quiz is finished");

        // If a question is already active, return it
        if (attempt.CurrentQuestionId != null)
        {
            var existingQuestion = await _context.Questions
                .FirstOrDefaultAsync(q => q.Id == attempt.CurrentQuestionId);

            if (existingQuestion == null)
                throw new Exception("Active question not found");

            return existingQuestion;
        }

        var userId = attempt.UserId;
        var level = attempt.CurrentLevel;

        var user = await _context.Users.FindAsync(userId);

        if (user == null)
            throw new Exception("User not found");

        // Questions seen across all quizzes
        var seenQuestionIds = await _context.UserQuestionHistories
            .Where(h => h.UserId == userId)
            .Select(h => h.QuestionId)
            .ToListAsync();

        if (CanRepeatQuestions(user))
        {
            seenQuestionIds.Clear();
        }

        // Questions already used in this attempt
        var usedInAttempt = attempt.Questions
            .Select(q => q.QuestionId)
            .ToList();

        // prefer target level but allow fallback to +/- 1 level if exhausted
        var questions = await _context.Questions
            .Where(q =>
                Math.Abs(q.Difficulty - level) <= 1 &&
                !seenQuestionIds.Contains(q.Id) &&
                !usedInAttempt.Contains(q.Id))
            .OrderBy(q => Math.Abs(q.Difficulty - level))
            .ToListAsync();

        var index = Random.Shared.Next(questions.Count);
        var question = questions[index];

        Console.WriteLine($"Level: {level}");
        Console.WriteLine($"Seen count: {seenQuestionIds.Count}");
        Console.WriteLine($"Used in attempt: {usedInAttempt.Count}");

        if (question == null)
            throw new Exception("No questions available");

        // Set current active question
        attempt.CurrentQuestionId = question.Id;

        await _context.SaveChangesAsync();

        return question;
    }

    public async Task<object> SubmitAnswer(SubmitAnswerRequest request, int currentUserId)
    {
        var attempt = await _context.QuizAttempts
            .FirstOrDefaultAsync(a => a.Id == request.AttemptId);

        if (attempt == null)
            throw new Exception("Quiz not found");

        if (attempt.UserId != currentUserId)
            throw new Exception("Unauthorized access");

        if (attempt.CurrentQuestionId != request.QuestionId)
            throw new Exception("Invalid question flow");

        attempt.CurrentQuestionId = null;

        var question = await _context.Questions
            .FirstOrDefaultAsync(q => q.Id == request.QuestionId);

        if (question == null)
            throw new Exception("Question not found");

        // Determine correctness using question data (MCQ-based)
        var data = JsonSerializer.Deserialize<QuestionData>(question.Data);

        if (data == null)
            throw new Exception("Invalid question data");

        // validate answer exists in options (allow blanks for timer rundown)
        if (!string.IsNullOrWhiteSpace(request.Answer) &&
            !data.Options.Contains(request.Answer))
        {
            throw new Exception("Invalid answer option");
        }

        bool correct = data.CorrectAnswer
            .Equals(request.Answer?.Trim(), StringComparison.OrdinalIgnoreCase);

        // Scoring
        int totalPoints = 0;
        var difficultyAtTime = attempt.CurrentLevel;

        if (correct)
        {
            int maxTime = 10000; // 10 seconds

            if (request.TimeTakenMs < maxTime)
            {
                double timeRatio = 1 - ((double)request.TimeTakenMs / maxTime);
                double timeScore = 1000 * timeRatio;

                double difficultyMultiplier = 1 + ((difficultyAtTime - 1) * 0.2);

                totalPoints = (int)(timeScore * difficultyMultiplier);
            }
        }

        // Update difficulty
        if (correct)
            attempt.CurrentLevel++;
        else
            attempt.CurrentLevel--;

        attempt.CurrentLevel = Math.Max(1, Math.Min(10, attempt.CurrentLevel));

        // Update user level
        var user = await _context.Users.FindAsync(attempt.UserId);

        if (user != null)
        {
            user.CurrentLevel = attempt.CurrentLevel;
        }

        // Save answered question
        var quizQuestion = new QuizAttemptQuestion
        {
            QuizAttemptId = attempt.Id,
            QuestionId = question.Id,
            Correct = correct,
            AnswerGiven = request.Answer,
            TimeTakenMs = request.TimeTakenMs,
            PointsAwarded = totalPoints,
            DifficultyAtTime = difficultyAtTime
        };

        _context.QuizAttemptQuestions.Add(quizQuestion);

        // Track history
        _context.UserQuestionHistories.Add(new UserQuestionHistory
        {
            UserId = attempt.UserId,
            QuestionId = question.Id
        });

        // Update score
        attempt.Score += totalPoints;

        // SAVE EVERYTHING FIRST
        await _context.SaveChangesAsync();

        // NOW count (includes this question)
        var questionCount = await _context.QuizAttemptQuestions
            .CountAsync(q => q.QuizAttemptId == attempt.Id);

        Console.WriteLine($"[DEBUG] QuestionCount AFTER SAVE: {questionCount}");

        // Completion check
        if (questionCount >= MaxQuestions)
        {
            Console.WriteLine("[DEBUG] Setting CompletedAt NOW");

            attempt.CompletedAt = DateTime.UtcNow;

            await _context.SaveChangesAsync(); // persist completion
        }

        return new
        {
            correct,
            totalPoints,
            newLevel = attempt.CurrentLevel,
            isComplete = attempt.CompletedAt != null
        };
    }

    public async Task<object> GetResults(int attemptId, int currentUserId)
    {
        var attempt = await _context.QuizAttempts
            .Include(a => a.Questions)
            .ThenInclude(q => q.Question)
            .FirstOrDefaultAsync(a => a.Id == attemptId);

        if (attempt == null)
            throw new Exception("Quiz not found");

        if (attempt.UserId != currentUserId)
            throw new Exception("Unauthorized access");

        if (attempt.CompletedAt == null)
            throw new Exception("Quiz not completed yet");

        var totalQuestions = attempt.Questions.Count;
        var correctAnswers = attempt.Questions.Count(q => q.Correct == true);

        var accuracy = totalQuestions == 0
            ? 0
            : Math.Round((double)correctAnswers / totalQuestions * 100, 2);

        var breakdown = attempt.Questions.Select(q =>
        {
            var data = JsonSerializer.Deserialize<QuestionData>(q.Question!.Data);

            return new
            {
                q.QuestionId,
                q.Question.Text,
                q.Correct,
                q.AnswerGiven,
                correctAnswer = data?.CorrectAnswer,
                q.PointsAwarded,
                q.DifficultyAtTime
            };
        });

        return new
        {
            attempt.Id,
            attempt.Score,
            totalQuestions,
            correctAnswers,
            accuracy,
            breakdown
        };
    }

    public async Task<int> GetUserIdFromEmail(string email)
    {
        var user = await _context.Users
            .FirstOrDefaultAsync(u => u.Email == email);

        if (user == null)
            throw new Exception("User not found");

        return user.Id;
    }

    public async Task<User> GetUser(int userId)
    {
        var user = await _context.Users.FindAsync(userId);
        if (user == null)
            throw new Exception("User not found");

        return user;
    }

    public async Task<object> UpdateDisplayName(int userId, string displayName)
    {
        if (string.IsNullOrWhiteSpace(displayName))
            throw new Exception("Display name is required");

        displayName = displayName.Trim();

        // basic validation (MVP)
        if (displayName.Length < 3 || displayName.Length > 20)
            throw new Exception("Display name must be 3-20 characters");

        if (!System.Text.RegularExpressions.Regex.IsMatch(displayName, "^[a-zA-Z0-9 ]+$"))
            throw new Exception("Only letters, numbers and spaces allowed");

        var lower = displayName.ToLower();

        var bannedWords = new[] { "badword1", "badword2" };

        if (bannedWords.Any(w => lower.Contains(w)))
            throw new Exception("Display name not allowed");

        var user = await _context.Users.FindAsync(userId);

        if (user == null)
            throw new Exception("User not found");

        user.DisplayName = displayName;
        user.IsNameAutoGenerated = false;

        await _context.SaveChangesAsync();

        return new { user.DisplayName };
    }

    public async Task<object> GetLeaderboard()
    {
        // users allowed on leaderboard
        var allowedUserIds = await _context.Users
            .Where(u => u.Role != Roles.Admin)
            .Select(u => u.Id)
            .ToListAsync();

        // aggregate scores per user
        var data = await _context.QuizAttempts
            .Where(a =>
                a.CompletedAt != null &&
                allowedUserIds.Contains(a.UserId))
            .GroupBy(a => a.UserId)
            .Select(g => new
            {
                UserId = g.Key,
                TotalScore = g.Sum(a => a.Score),
                Attempts = g.Count()
            })
            .OrderByDescending(x => x.TotalScore)
            .Take(10)
            .ToListAsync();

        var userIds = data.Select(x => x.UserId).ToList();

        var users = await _context.Users
            .Where(u => userIds.Contains(u.Id))
            .ToDictionaryAsync(u => u.Id);

        var result = data
            .Select((x, index) => new
            {
                userId = x.UserId,
                rank = index + 1,
                displayName = users[x.UserId].DisplayName,
                totalScore = x.TotalScore,
                attempts = x.Attempts
            });

        return result;
    } 

    public async Task<object> GetUserStats(int userId)
    {
        var attempts = await _context.QuizAttempts
            .Include(a => a.Questions)
            .Where(a => a.UserId == userId && a.CompletedAt != null)
            .ToListAsync();

        if (!attempts.Any())
        {
            return new
            {
                totalAttempts = 0,
                totalScore = 0,
                averageScore = 0,
                bestScore = 0,
                averageAccuracy = 0
            };
        }

        var totalAttempts = attempts.Count;
        var totalScore = attempts.Sum(a => a.Score);
        var averageScore = Math.Round(attempts.Average(a => a.Score), 2);
        var bestScore = attempts.Max(a => a.Score);

        var allQuestions = attempts.SelectMany(a => a.Questions);

        var totalQuestions = allQuestions.Count();
        var correctAnswers = allQuestions.Count(q => q.Correct == true);

        var averageAccuracy = totalQuestions == 0
            ? 0
            : Math.Round((double)correctAnswers / totalQuestions * 100, 2);

        return new
        {
            totalAttempts,
            totalScore,
            averageScore,
            bestScore,
            averageAccuracy
        };
    }

    public async Task<List<Question>> GetAllQuestions()
    {
        return await _context.Questions
            .OrderBy(q => q.Difficulty)
            .ToListAsync();
    }

    public async Task<Question> CreateQuestion(CreateQuestionRequest request)
    {
        var data = new QuestionData
        {
            Options = request.Options,
            CorrectAnswer = request.CorrectAnswer
        };

        var question = new Question
        {
            Text = request.Text,
            Difficulty = request.Difficulty,
            Category = request.Category,
            Type = request.Type,
            Data = JsonSerializer.Serialize(data)
        };

        _context.Questions.Add(question);

        await _context.SaveChangesAsync();

        return question;
    }

    public async Task<Question?> GetQuestionById(int id)
    {
        return await _context.Questions
            .FirstOrDefaultAsync(q => q.Id == id);
    }

    public async Task<Question?> UpdateQuestion(int id, CreateQuestionRequest request)
    {
        var question = await _context.Questions
            .FirstOrDefaultAsync(q => q.Id == id);

        if (question == null)
            return null;

        var data = new QuestionData
        {
            Options = request.Options,
            CorrectAnswer = request.CorrectAnswer
        };

        question.Text = request.Text;
        question.Difficulty = request.Difficulty;
        question.Category = request.Category;
        question.Type = request.Type;

        question.Data = JsonSerializer.Serialize(data);

        await _context.SaveChangesAsync();

        return question;
    }

    public async Task<BugReport> CreateBugReport(
        int userId,
        CreateBugReportRequest request)
    {
        var user = await _context.Users.FindAsync(userId);

        if (user == null)
            throw new Exception("User not found");

        if (user.Role == Roles.Admin)
            throw new Exception("Admins cannot submit bug reports");

        var report = new BugReport
        {
            UserId = userId,
            Title = request.Title,
            Description = request.Description,
            Status = "Open",
            Severity = BugSeverities.Medium,
            CreatedAt = DateTime.UtcNow
        };

        _context.BugReports.Add(report);

        await _context.SaveChangesAsync();

        return report;
    }

    public async Task<List<BugReportResponse>> GetAllBugReports()
    {
        return await _context.BugReports
            .Include(x => x.User)
            .OrderByDescending(x => x.CreatedAt)
            .Select(x => new BugReportResponse
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description,
                Status = x.Status,
                Severity = x.Severity,
                CreatedAt = x.CreatedAt,
                DisplayName = x.User!.DisplayName
            })
            .ToListAsync();
    }

    public async Task<List<BugReport>> GetUserBugReports(int userId)
    {
        return await _context.BugReports
            .Where(x => x.UserId == userId)
            .OrderByDescending(x => x.CreatedAt)
            .ToListAsync();
    }

    public async Task<BugReport?> UpdateBug(
        int id, 
        UpdateBugRequest request)
    {
        var bug = await _context.BugReports
            .FirstOrDefaultAsync(x => x.Id == id);

        if (bug == null)
            return null;

        var allowed = new[]
        {
        "Open",
        "In Progress",
        "Resolved",
        "Closed"
    };

        if (!allowed.Contains(request.Status))
            throw new Exception("Invalid status");

        if (request.Severity != BugSeverities.Low &&
            request.Severity != BugSeverities.Medium &&
            request.Severity != BugSeverities.High &&
            request.Severity != BugSeverities.Critical)
        {
            throw new Exception("Invalid severity");
        }

        bug.Status = request.Status;
        bug.Severity = request.Severity;

        await _context.SaveChangesAsync();

        return bug;
    }

    public async Task<BugComment> AddBugComment(
        int bugId,
        int userId,
        CreateBugCommentRequest request)
    {
        var bug = await _context.BugReports
            .FirstOrDefaultAsync(x => x.Id == bugId);

        if (bug == null)
            throw new Exception("Bug not found");

        if (string.IsNullOrWhiteSpace(request.Comment))
            throw new Exception("Comment is required");

        var comment = new BugComment
        {
            BugReportId = bugId,
            UserId = userId,
            Comment = request.Comment.Trim(),
            CreatedAt = DateTime.UtcNow
        };

        _context.BugComments.Add(comment);

        await _context.SaveChangesAsync();

        return comment;
    }

    public async Task<List<BugCommentResponse>> GetBugComments(int bugId)
    {
        return await _context.BugComments
            .Include(x => x.User)
            .Where(x => x.BugReportId == bugId)
            .OrderBy(x => x.CreatedAt)
            .Select(x => new BugCommentResponse
            {
                Id = x.Id,
                Comment = x.Comment,
                CreatedAt = x.CreatedAt,
                DisplayName = x.User!.DisplayName,
                Role = x.User.Role
            })
            .ToListAsync();
    }

    public async Task<BugReportResponse?> GetBugReport(int id)
    {
        return await _context.BugReports
            .Include(x => x.User)
            .Where(x => x.Id == id)
            .Select(x => new BugReportResponse
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description,
                Status = x.Status,
                Severity = x.Severity,
                CreatedAt = x.CreatedAt,
                DisplayName = x.User!.DisplayName
            })
            .FirstOrDefaultAsync();
    }

    public async Task<bool> UserOwnsBug(
    int bugId,
    int userId)
    {
        return await _context.BugReports
            .AnyAsync(x =>
                x.Id == bugId &&
                x.UserId == userId);
    }

    public async Task<BugReportResponse?> GetUserBug(
    int bugId,
    int userId)
    {
        var bug = await _context.BugReports
            .Where(x =>
                x.Id == bugId &&
                x.UserId == userId)
            .Select(x => new BugReportResponse
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description,
                Status = x.Status,
                Severity = x.Severity,
                CreatedAt = x.CreatedAt,
                DisplayName = x.User!.DisplayName
            })
            .FirstOrDefaultAsync();

        return bug;
    }

}