using AdaptiveQuiz.Api.Data;
using AdaptiveQuiz.Api.Domain;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace AdaptiveQuiz.Api.Services;

public class QuizService
{
    private readonly AppDbContext _context;
    const int MaxQuestions = 3;
    bool isDev = true;
    private static readonly string[] Adjectives =
        { "Swift", "Clever", "Brave", "Curious", "Lucky" };
    private static readonly string[] Animals =
        { "Tiger", "Fox", "Eagle", "Shark", "Wolf" };

    public QuizService(AppDbContext context)
    {
        _context = context;
    }

    private string GenerateDisplayName()
    {
        var rand = Random.Shared;

        var adj = Adjectives[rand.Next(Adjectives.Length)];
        var animal = Animals[rand.Next(Animals.Length)];
        var number = rand.Next(10, 99);

        return $"{adj}{animal}{number}";
    }

    public async Task<QuizAttempt> StartQuizForUser(string email)
    {
        var user = await _context.Users
            .FirstOrDefaultAsync(u => u.Email == email);

        if (user == null)
        {
            user = new User
            {
                Email = email,
                Role = "User",
                CurrentLevel = 1,
                DisplayName = GenerateDisplayName(),
                IsNameAutoGenerated = true
            };

            _context.Users.Add(user);
            await _context.SaveChangesAsync();
        }

        return await StartQuiz(user.Id);
    }

    public async Task<QuizAttempt> StartQuiz(int userId)
    {
        var user = await _context.Users.FindAsync(userId);

        if (user == null)
            throw new Exception("User not found");

        // Monthly restriction
        if (user.Role == "User" && user.LastQuizAt.HasValue && !isDev)
        {
            var now = DateTime.UtcNow;
            var last = user.LastQuizAt.Value;

            if (last.Month == now.Month && last.Year == now.Year)
                throw new Exception("User has already taken quiz this month");
        }

        var attempt = new QuizAttempt
        {
            UserId = user.Id,
            StartedAt = DateTime.UtcNow,
            StartingLevel = user.CurrentLevel,
            CurrentLevel = user.CurrentLevel,
            Score = 0
        };

        _context.QuizAttempts.Add(attempt);

        user.LastQuizAt = DateTime.UtcNow;

        await _context.SaveChangesAsync();

        return attempt;
    }

    public async Task<Question> GetNextQuestion(int attemptId, int currentUserId)
    {
        var attempt = await _context.QuizAttempts
            .Include(a => a.Questions)
            .FirstOrDefaultAsync(a => a.Id == attemptId);

        if (attempt == null)
            throw new Exception("Quiz not found");

        if (attempt.UserId != currentUserId)
            throw new Exception("Unauthorized access");

        // Already completed
        if (attempt.CompletedAt != null)
            throw new Exception("Quiz already completed");

        // Reached max questions
        if (attempt.Questions.Count >= 10)
            throw new Exception("Quiz is finished");

        // If a question is already active, return it
        if (attempt.CurrentQuestionId != null)
        {
            var existingQuestion = await _context.Questions
                .FirstOrDefaultAsync(q => q.Id == attempt.CurrentQuestionId);

            if (existingQuestion == null)
                throw new Exception("Active question not found");

            return existingQuestion;
        }

        var userId = attempt.UserId;
        var level = attempt.CurrentLevel;

        // Questions seen across all quizzes
        var seenQuestionIds = await _context.UserQuestionHistories
            .Where(h => h.UserId == userId)
            .Select(h => h.QuestionId)
            .ToListAsync();

        if (isDev)
        {
            seenQuestionIds.Clear();
        }

        // Questions already used in this attempt
        var usedInAttempt = attempt.Questions
            .Select(q => q.QuestionId)
            .ToList();

        // prefer target level but allow fallback to +/- 1 level if exhausted
        var questions = await _context.Questions
            .Where(q =>
                Math.Abs(q.Difficulty - level) <= 1 &&
                !seenQuestionIds.Contains(q.Id) &&
                !usedInAttempt.Contains(q.Id))
            .OrderBy(q => Math.Abs(q.Difficulty - level))
            .ToListAsync();

        var index = Random.Shared.Next(questions.Count);
        var question = questions[index];

        Console.WriteLine($"Level: {level}");
        Console.WriteLine($"Seen count: {seenQuestionIds.Count}");
        Console.WriteLine($"Used in attempt: {usedInAttempt.Count}");

        if (question == null)
            throw new Exception("No questions available");

        // Set current active question
        attempt.CurrentQuestionId = question.Id;

        await _context.SaveChangesAsync();

        return question;
    }

    public async Task<object> SubmitAnswer(SubmitAnswerRequest request, int currentUserId)
    {
        var attempt = await _context.QuizAttempts
            .FirstOrDefaultAsync(a => a.Id == request.AttemptId);

        if (attempt == null)
            throw new Exception("Quiz not found");

        if (attempt.UserId != currentUserId)
            throw new Exception("Unauthorized access");

        if (attempt.CurrentQuestionId != request.QuestionId)
            throw new Exception("Invalid question flow");

        attempt.CurrentQuestionId = null;

        var question = await _context.Questions
            .FirstOrDefaultAsync(q => q.Id == request.QuestionId);

        if (question == null)
            throw new Exception("Question not found");

        // Determine correctness using question data (MCQ-based)
        var data = JsonSerializer.Deserialize<QuestionData>(question.Data);

        if (data == null)
            throw new Exception("Invalid question data");

        // validate answer exists in options 
        if (!data.Options.Contains(request.Answer))
            throw new Exception("Invalid answer option");

        bool correct = data.CorrectAnswer
            .Equals(request.Answer?.Trim(), StringComparison.OrdinalIgnoreCase);

        // Scoring
        int totalPoints = 0;
        var difficultyAtTime = attempt.CurrentLevel;

        if (correct)
        {
            int maxTime = 10000; // 10 seconds

            if (request.TimeTakenMs < maxTime)
            {
                double timeRatio = 1 - ((double)request.TimeTakenMs / maxTime);
                double timeScore = 1000 * timeRatio;

                double difficultyMultiplier = 1 + ((difficultyAtTime - 1) * 0.1);

                totalPoints = (int)(timeScore * difficultyMultiplier);
            }
        }

        // Update difficulty
        if (correct)
            attempt.CurrentLevel++;
        else
            attempt.CurrentLevel--;

        attempt.CurrentLevel = Math.Max(1, Math.Min(10, attempt.CurrentLevel));

        // Save answered question
        var quizQuestion = new QuizAttemptQuestion
        {
            QuizAttemptId = attempt.Id,
            QuestionId = question.Id,
            Correct = correct,
            AnswerGiven = request.Answer,
            TimeTakenMs = request.TimeTakenMs,
            PointsAwarded = totalPoints,
            DifficultyAtTime = difficultyAtTime
        };

        _context.QuizAttemptQuestions.Add(quizQuestion);

        // Track history
        _context.UserQuestionHistories.Add(new UserQuestionHistory
        {
            UserId = attempt.UserId,
            QuestionId = question.Id
        });

        // Update score
        attempt.Score += totalPoints;

        // SAVE EVERYTHING FIRST
        await _context.SaveChangesAsync();

        // NOW count (includes this question)
        var questionCount = await _context.QuizAttemptQuestions
            .CountAsync(q => q.QuizAttemptId == attempt.Id);

        Console.WriteLine($"[DEBUG] QuestionCount AFTER SAVE: {questionCount}");

        // Completion check
        if (questionCount >= MaxQuestions)
        {
            Console.WriteLine("[DEBUG] Setting CompletedAt NOW");

            attempt.CompletedAt = DateTime.UtcNow;

            await _context.SaveChangesAsync(); // persist completion
        }

        return new
        {
            correct,
            totalPoints,
            newLevel = attempt.CurrentLevel,
            isComplete = attempt.CompletedAt != null
        };
    }

    public async Task<object> GetResults(int attemptId, int currentUserId)
    {
        var attempt = await _context.QuizAttempts
            .Include(a => a.Questions)
            .ThenInclude(q => q.Question)
            .FirstOrDefaultAsync(a => a.Id == attemptId);

        if (attempt == null)
            throw new Exception("Quiz not found");

        if (attempt.UserId != currentUserId)
            throw new Exception("Unauthorized access");

        if (attempt.CompletedAt == null)
            throw new Exception("Quiz not completed yet");

        var totalQuestions = attempt.Questions.Count;
        var correctAnswers = attempt.Questions.Count(q => q.Correct == true);

        var accuracy = totalQuestions == 0
            ? 0
            : Math.Round((double)correctAnswers / totalQuestions * 100, 2);

        var breakdown = attempt.Questions.Select(q => new
        {
            q.QuestionId,
            q.Question!.Text,
            q.Correct,
            q.AnswerGiven,
            q.PointsAwarded,
            q.DifficultyAtTime
        });

        return new
        {
            attempt.Id,
            attempt.Score,
            totalQuestions,
            correctAnswers,
            accuracy,
            breakdown
        };
    }

    public async Task<int> GetUserIdFromEmail(string email)
    {
        var user = await _context.Users
            .FirstOrDefaultAsync(u => u.Email == email);

        if (user == null)
            throw new Exception("User not found");

        return user.Id;
    }

    public async Task<object> UpdateDisplayName(int userId, string displayName)
    {
        if (string.IsNullOrWhiteSpace(displayName))
            throw new Exception("Display name is required");

        displayName = displayName.Trim();

        // basic validation (MVP)
        if (displayName.Length < 3 || displayName.Length > 20)
            throw new Exception("Display name must be 3-20 characters");

        if (!System.Text.RegularExpressions.Regex.IsMatch(displayName, "^[a-zA-Z0-9 ]+$"))
            throw new Exception("Only letters, numbers and spaces allowed");

        var lower = displayName.ToLower();

        var bannedWords = new[] { "badword1", "badword2" };

        if (bannedWords.Any(w => lower.Contains(w)))
            throw new Exception("Display name not allowed");

        var user = await _context.Users.FindAsync(userId);

        if (user == null)
            throw new Exception("User not found");

        user.DisplayName = displayName;
        user.IsNameAutoGenerated = false;

        await _context.SaveChangesAsync();

        return new { user.DisplayName };
    }

    public async Task<object> GetLeaderboard()
    {
        // aggregate scores per user
        var data = await _context.QuizAttempts
            .Where(a => a.CompletedAt != null)
            .GroupBy(a => a.UserId)
            .Select(g => new
            {
                UserId = g.Key,
                TotalScore = g.Sum(a => a.Score),
                Attempts = g.Count()
            })
            .OrderByDescending(x => x.TotalScore)
            .Take(10)
            .ToListAsync();

        var userIds = data.Select(x => x.UserId).ToList();

        var users = await _context.Users
            .Where(u => userIds.Contains(u.Id))
            .ToDictionaryAsync(u => u.Id);

        var result = data
            .Select((x, index) => new
            {
                rank = index + 1,
                displayName = users.ContainsKey(x.UserId)
                    ? users[x.UserId].DisplayName
                    : "Unknown",
                totalScore = x.TotalScore,
                attempts = x.Attempts
            });

        return result;
    }

    public async Task<object> GetUserStats(int userId)
    {
        var attempts = await _context.QuizAttempts
            .Include(a => a.Questions)
            .Where(a => a.UserId == userId && a.CompletedAt != null)
            .ToListAsync();

        if (!attempts.Any())
        {
            return new
            {
                totalAttempts = 0,
                totalScore = 0,
                averageScore = 0,
                bestScore = 0,
                averageAccuracy = 0
            };
        }

        var totalAttempts = attempts.Count;
        var totalScore = attempts.Sum(a => a.Score);
        var averageScore = Math.Round(attempts.Average(a => a.Score), 2);
        var bestScore = attempts.Max(a => a.Score);

        var allQuestions = attempts.SelectMany(a => a.Questions);

        var totalQuestions = allQuestions.Count();
        var correctAnswers = allQuestions.Count(q => q.Correct == true);

        var averageAccuracy = totalQuestions == 0
            ? 0
            : Math.Round((double)correctAnswers / totalQuestions * 100, 2);

        return new
        {
            totalAttempts,
            totalScore,
            averageScore,
            bestScore,
            averageAccuracy
        };
    }

}