using AdaptiveQuiz.Api.Data;
using AdaptiveQuiz.Api.Domain;
using AdaptiveQuiz.Api.Exceptions;
using AdaptiveQuiz.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;

namespace AdaptiveQuiz.Api.Services
{
    public class UserService
    {
        private readonly AppDbContext _context;
        private static readonly string[] Adjectives =
            { "Swift", "Clever", "Brave", "Curious", "Lucky" };
        private static readonly string[] Animals =
            { "Tiger", "Fox", "Eagle", "Shark", "Wolf" };

        public UserService(AppDbContext context)
        {
            _context = context;
        }

        private string GenerateDisplayName()
        {
            var rand = Random.Shared;
            var adj = Adjectives[rand.Next(Adjectives.Length)];
            var animal = Animals[rand.Next(Animals.Length)];
            var number = rand.Next(10, 99);

            return $"{adj}{animal}{number}";
        }

        public async Task<User> GetOrCreateUserAsync(string email)
        {
            var user = await _context.Users
                .FirstOrDefaultAsync(u => u.Email == email);

            if (user == null)
            {
                user = new User
                {
                    Email = email,
                    Role = Roles.User,
                    CurrentLevel = 1,
                    DisplayName = GenerateDisplayName(),
                    IsNameAutoGenerated = true
                };

                _context.Users.Add(user);
                await _context.SaveChangesAsync();
            }

            return user;
        }

        public async Task<int> GetUserIdFromEmail(string email)
        {
            var user = await _context.Users
                .FirstOrDefaultAsync(u => u.Email == email);

            if (user == null)
                throw new UserNotFoundException();

            return user.Id;
        }

        public async Task<User> GetUser(int userId)
        {
            var user = await _context.Users.FindAsync(userId);
            if (user == null)
                throw new UserNotFoundException();

            return user;
        }

        public async Task<object> UpdateDisplayName(int userId, string displayName)
        {
            if (string.IsNullOrWhiteSpace(displayName))
                throw new InvalidDisplayNameException("Display name is required");

            displayName = displayName.Trim();

            if (displayName.Length < 3 || displayName.Length > 20)
                throw new InvalidDisplayNameException("Display name must be 3-20 characters");

            if (!System.Text.RegularExpressions.Regex.IsMatch(displayName, "^[a-zA-Z0-9 ]+$"))
                throw new InvalidDisplayNameException("Only letters, numbers and spaces allowed");

            var lower = displayName.ToLower();

            var bannedWords = new[] { "badword1", "badword2" };

            if (bannedWords.Any(w => lower.Contains(w)))
                throw new InvalidDisplayNameException("Display name not allowed");

            var user = await _context.Users.FindAsync(userId);

            if (user == null)
                throw new UserNotFoundException();

            user.DisplayName = displayName;
            user.IsNameAutoGenerated = false;

            await _context.SaveChangesAsync();

            return new
            {
                user.DisplayName
            };
        }
    }
}
