import { useState } from "react";
import { useUpdateDisplayName, useMe } from "../hooks/useQuiz";
import { useUser } from "../context/UserContext";
import { useNavigate } from "react-router-dom";
import { UserCircleIcon, PencilSquareIcon } from "@heroicons/react/24/outline";

export default function ProfilePage() {
    const { data: me, isLoading } = useMe();
    const updateName = useUpdateDisplayName();
    const { setDisplayName } = useUser();
    const navigate = useNavigate();

    const [newName, setNewName] = useState("");
    const [editing, setEditing] = useState(false);

    const handleUpdate = async () => {
        if (!newName) return;
        console.log("[UI] Update display name clicked", newName);

        await updateName.mutateAsync(newName);
        setDisplayName(newName);
        setNewName("");
        setEditing(false);
        console.log("[UI] Update complete");
    };

    if (isLoading || !me) {
        return <p className="text-center text-gray-400">Loading profile...</p>;
    }

    return (
        <div className="space-y-8">
            {/* Title */}
            <div className="text-center space-y-2">
                <UserCircleIcon className="w-10 h-10 mx-auto text-gray-400" />
                <h1 className="text-3xl font-bold">Your Profile</h1>
            </div>

            {/* Display Name Card */}
            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 space-y-4">
                <div className="flex items-center justify-between">
                    <h2 className="text-lg font-semibold">Display Name</h2>

                    {!editing && (
                        <button onClick={() => setEditing(true)} className="text-sm text-blue-400 hover:text-blue-300 flex items-center gap-1">
                            <PencilSquareIcon className="w-4 h-4" />
                            Edit
                        </button>
                    )}
                </div>

                {!editing ? (
                    <div className="space-y-2">
                        <div className="text-xl font-semibold text-white">{me.displayName}</div>

                        {me.isNameAutoGenerated && <p className="text-sm text-gray-400">This name was auto-generated. You can change it anytime.</p>}
                    </div>
                ) : (
                    <div className="space-y-3">
                        <input
                            value={newName}
                            onChange={(e) => setNewName(e.target.value)}
                            placeholder="Enter new display name"
                            className="w-full p-3 rounded text-black"
                        />

                        <div className="flex gap-2">
                            <button onClick={handleUpdate} className="flex-1 bg-white text-black py-2 rounded-lg font-semibold">
                                Save
                            </button>

                            <button
                                onClick={() => {
                                    setEditing(false);
                                    setNewName("");
                                }}
                                className="flex-1 border border-gray-600 py-2 rounded-lg">
                                Cancel
                            </button>
                        </div>
                    </div>
                )}
            </div>

            {/* Quick Actions (optional but nice) */}
            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 space-y-3 text-center">
                <h2 className="text-lg font-semibold">Quick Actions</h2>

                <button onClick={() => navigate("/stats")} className="w-full border border-gray-600 py-2 rounded-lg">
                    View Stats
                </button>
            </div>
        </div>
    );
}
