import { useState, useEffect } from "react";
import { useStartQuiz, useNextQuestion, useAnswer, useMe } from "../hooks/useQuiz";
import { useUser } from "../context/UserContext";
import { useNavigate } from "react-router-dom";
import { SparklesIcon, LockClosedIcon, PencilSquareIcon } from "@heroicons/react/24/outline";

export default function QuizPage() {
    const [attemptId, setAttemptId] = useState<number | null>(null);
    const [selected, setSelected] = useState<string>("");
    const [startTime, setStartTime] = useState<number>(0);
    const [dismissed, setDismissed] = useState(false);

    const startQuiz = useStartQuiz();
    const answerMutation = useAnswer();
    const navigate = useNavigate();

    const { displayName } = useUser();
    const { data: me } = useMe();

    const { data: question, isLoading, isError, refetch } = useNextQuestion(attemptId);
    const showNamePrompt = me?.isNameAutoGenerated && !dismissed;

    const handleStart = async () => {
        const res = await startQuiz.mutateAsync();
        setAttemptId(res.id);
    };

    const handleAnswer = async () => {
        if (!question || !attemptId) return;

        const timeTakenMs = Date.now() - startTime;

        const res = await answerMutation.mutateAsync({
            attemptId,
            questionId: question.id,
            answer: selected,
            timeTakenMs,
        });

        setSelected("");
        setStartTime(0);

        if (res.isComplete) {
            navigate("/results", { state: { attemptId } });
        } else {
            refetch();
        }
    };

    // start timer when question changes
    useEffect(() => {
        if (question) {
            setStartTime(Date.now());
        }
    }, [question]);

    function hasPlayedThisMonth(lastQuizAt?: string | null) {
        if (!lastQuizAt) return false;

        const last = new Date(lastQuizAt);
        const now = new Date();

        return last.getMonth() === now.getMonth() && last.getFullYear() === now.getFullYear();
    }

    const canPlay = !hasPlayedThisMonth(me?.lastQuizAt);

    return (
        <div className="space-y-6">
            {/* Greeting */}
            {displayName && (
                <div className="text-center text-gray-300">
                    Hi, <span className="font-semibold text-white">{displayName}</span>
                </div>
            )}

            {showNamePrompt && (
                <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 flex items-center justify-between gap-3">
                    <div className="flex items-center gap-2 text-sm text-gray-300">
                        <PencilSquareIcon className="w-4 h-4 text-blue-400" />
                        <span>Want to change your display name?</span>
                    </div>

                    <button
                        onClick={() => {
                            setDismissed(true);
                            navigate("/profile");
                        }}
                        className="text-sm text-blue-400 hover:text-blue-300">
                        Edit
                    </button>
                </div>
            )}

            {/* Intro Card */}
            {!attemptId && (
                <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 space-y-4">
                    <div className="flex items-center gap-2">
                        {canPlay ? <SparklesIcon className="w-5 h-5 text-blue-400" /> : <LockClosedIcon className="w-5 h-5 text-gray-400" />}

                        <h2 className="text-lg font-semibold">{canPlay ? "Monthly Challenge" : "Quiz Completed"}</h2>
                    </div>

                    {canPlay ? (
                        <p className="text-gray-300 text-sm">
                            You haven’t completed this month’s quiz yet. Take on <span className="text-white font-medium">10 adaptive questions</span>{" "}
                            and see how you rank.
                        </p>
                    ) : (
                        <p className="text-gray-400 text-sm">You’ve already completed this month’s quiz. Come back next month for a new challenge.</p>
                    )}

                    {/* Action */}
                    {canPlay ? (
                        <button
                            onClick={handleStart}
                            className="w-full bg-white text-black py-3 rounded-lg font-semibold hover:opacity-90 transition">
                            Start Quiz
                        </button>
                    ) : (
                        <button disabled className="w-full bg-gray-700 text-gray-400 py-3 rounded-lg font-semibold">
                            Quiz Completed
                        </button>
                    )}
                </div>
            )}

            {/* Loading */}
            {isLoading && <p className="text-center text-gray-400">Loading question...</p>}

            {/* Error */}
            {isError && <p className="text-center text-red-400">Something went wrong</p>}

            {/* Question */}
            {question && (
                <div className="space-y-6">
                    <h2 className="text-xl font-semibold text-center">{question.text}</h2>

                    <div className="space-y-2">
                        {question.options?.map((opt: string) => (
                            <button
                                key={opt}
                                onClick={() => setSelected(opt)}
                                className={`w-full p-3 rounded-lg border transition ${
                                    selected === opt ? "bg-white text-black" : "border-gray-600 hover:border-gray-400"
                                }`}>
                                {opt}
                            </button>
                        ))}
                    </div>

                    <button
                        disabled={!selected || answerMutation.isPending}
                        onClick={handleAnswer}
                        className="w-full bg-green-500 py-3 rounded-lg font-semibold disabled:opacity-50 hover:opacity-90 transition">
                        {answerMutation.isPending ? "Submitting..." : "Submit Answer"}
                    </button>
                </div>
            )}
        </div>
    );
}
