import { useState, useEffect } from "react";
import { useStartQuiz, useNextQuestion, useAnswer, useMe } from "../hooks/useQuiz";
import { useUser } from "../context/UserContext";
import { useNavigate } from "react-router-dom";
import { SparklesIcon, LockClosedIcon, PencilSquareIcon } from "@heroicons/react/24/outline";
import { useQueryClient } from "@tanstack/react-query";

export default function QuizPage() {
    const [attemptId, setAttemptId] = useState<number | null>(null);
    const [selected, setSelected] = useState("");
    const [startTime, setStartTime] = useState(0);
    const [dismissed, setDismissed] = useState(false);
    const [timeLeft, setTimeLeft] = useState(10);
    const [hasTimedOut, setHasTimedOut] = useState(false);
    const [currentScore, setCurrentScore] = useState(0);
    const [currentLevel, setCurrentLevel] = useState(1);

    const startQuiz = useStartQuiz();
    const answerMutation = useAnswer();
    const navigate = useNavigate();
    const queryClient = useQueryClient();

    const { displayName, canPlay } = useUser();
    const { data: me } = useMe();

    const { data: question, isLoading, isError, refetch } = useNextQuestion(attemptId);
    const showNamePrompt = me?.isNameAutoGenerated && !dismissed;

    const handleStart = async () => {
        const res = await startQuiz.mutateAsync();
        setCurrentScore(0);
        setCurrentLevel(res.startingLevel);
        setAttemptId(res.id);
    };

    const handleTimeout = async () => {
        if (!question || !attemptId) return;

        const res = await answerMutation.mutateAsync({
            attemptId,
            questionId: question.id,
            answer: "",
            timeTakenMs: 10000,
        });

        if (res.isComplete) {
            queryClient.invalidateQueries({ queryKey: ["stats"] });
            queryClient.invalidateQueries({ queryKey: ["leaderboard"] });
            queryClient.invalidateQueries({ queryKey: ["me"] });

            navigate("/results", {
                state: { attemptId },
            });
        } else {
            refetch();
        }
    };

    const handleAnswer = async () => {
        if (!question || !attemptId) return;

        const timeTakenMs = Date.now() - startTime;

        const res = await answerMutation.mutateAsync({
            attemptId,
            questionId: question.id,
            answer: selected,
            timeTakenMs,
        });

        setSelected("");
        setStartTime(0);
        setCurrentScore((prev) => prev + res.totalPoints);
        setCurrentLevel(res.newLevel);

        if (res.isComplete) {
            // invalidate everything affected by quiz completion
            queryClient.invalidateQueries({ queryKey: ["stats"] });
            queryClient.invalidateQueries({ queryKey: ["leaderboard"] });
            queryClient.invalidateQueries({ queryKey: ["me"] });
            navigate("/results", { state: { attemptId } });
        } else {
            refetch();
        }
    };

    // start timer when question changes
    useEffect(() => {
        if (question) {
            setStartTime(Date.now());
        }
    }, [question]);

    useEffect(() => {
        if (!question) return;

        setTimeLeft(10);
        setHasTimedOut(false);
    }, [question]);

    // Countdown effect
    useEffect(() => {
        if (!question) return;

        if (timeLeft <= 0 && !hasTimedOut) {
            setHasTimedOut(true);
            handleTimeout();
            return;
        }

        const timer = setTimeout(() => {
            setTimeLeft((prev) => prev - 1);
        }, 1000);

        return () => clearTimeout(timer);
    }, [timeLeft, question]);

    return (
        <div className="space-y-6">
            {/* Greeting */}
            {displayName && (
                <div className="text-center text-gray-300">
                    Hi, <span className="font-semibold text-white">{displayName}</span>
                </div>
            )}

            {showNamePrompt && (
                <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 flex items-center justify-between gap-3">
                    <div className="flex items-center gap-2 text-sm text-gray-300">
                        <PencilSquareIcon className="w-4 h-4 text-blue-400" />
                        <span>Want to change your display name?</span>
                    </div>

                    <button
                        onClick={() => {
                            setDismissed(true);
                            navigate("/profile");
                        }}
                        className="text-sm text-blue-400 hover:text-blue-300">
                        Edit
                    </button>
                </div>
            )}

            {/* Intro Card */}
            {!attemptId && (
                <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 space-y-4">
                    <div className="flex items-center gap-2">
                        {canPlay ? <SparklesIcon className="w-5 h-5 text-blue-400" /> : <LockClosedIcon className="w-5 h-5 text-gray-400" />}

                        <h2 className="text-lg font-semibold">{canPlay ? "Monthly Challenge" : "Quiz Completed"}</h2>
                    </div>

                    {canPlay ? (
                        <p className="text-gray-300 text-sm">
                            You haven’t completed this month’s quiz yet. Take on <span className="text-white font-medium">10 adaptive questions</span>{" "}
                            and see how you rank.
                        </p>
                    ) : (
                        <p className="text-gray-400 text-sm">You’ve already completed this month’s quiz. Come back next month for a new challenge.</p>
                    )}

                    {/* Action */}
                    {canPlay ? (
                        <button
                            onClick={handleStart}
                            className="w-full bg-white text-black py-3 rounded-lg font-semibold hover:opacity-90 transition">
                            Start Quiz
                        </button>
                    ) : (
                        <button disabled className="w-full bg-gray-700 text-gray-400 py-3 rounded-lg font-semibold">
                            Quiz Completed
                        </button>
                    )}
                </div>
            )}

            {/* Loading */}
            {isLoading && <p className="text-center text-gray-400">Loading question...</p>}

            {/* Error */}
            {isError && <p className="text-center text-red-400">Something went wrong</p>}

            {/* Question */}
            {question && (
                <div className="space-y-6">
                    <div className="flex items-center justify-between gap-3">
                        <div className="rounded-full border border-gray-700 bg-gray-900 px-4 py-2 text-sm font-medium text-gray-300">
                            Score {currentScore}
                        </div>

                        <div
                            className={`flex h-16 w-16 items-center justify-center rounded-full text-2xl font-bold transition ${
                                timeLeft <= 3 ? "bg-red-500 text-white animate-pulse" : "bg-gray-800 text-white"
                            }`}>
                            {timeLeft}
                        </div>

                        <div className="rounded-full border border-blue-500/30 bg-blue-500/10 px-4 py-2 text-sm font-medium text-blue-300">
                            Level {currentLevel}
                        </div>
                    </div>

                    <h2 className="text-xl font-semibold text-center">{question.text}</h2>

                    <div className="space-y-2">
                        {question.options?.map((opt: string) => (
                            <button
                                key={opt}
                                onClick={() => setSelected(opt)}
                                className={`w-full p-3 rounded-lg border transition ${
                                    selected === opt ? "bg-white text-black" : "border-gray-600 hover:border-gray-400"
                                }`}>
                                {opt}
                            </button>
                        ))}
                    </div>

                    <button
                        disabled={!selected || answerMutation.isPending}
                        onClick={handleAnswer}
                        className="w-full bg-green-500 py-3 rounded-lg font-semibold disabled:opacity-50 hover:opacity-90 transition">
                        {answerMutation.isPending ? "Submitting..." : "Submit Answer"}
                    </button>
                </div>
            )}
        </div>
    );
}
