namespace AdaptiveQuiz.Api.DTOs.Responses;

public class CurrentUserResponse
{
    public int Id { get; set; }

    public string DisplayName { get; set; } = "";
    public DateTime? LastQuizAt { get; set; }
    public bool IsNameAutoGenerated { get; set; }
    public string Role { get; set; } = "";

    public bool CanPlay { get; set; }
    public bool CanManageQuestions { get; set; }
    public bool CanEnterLeaderboard { get; set; }
}