using AdaptiveQuiz.Api.Domain;
using AdaptiveQuiz.Api.Infrastructure;
using AdaptiveQuiz.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.Json;

namespace AdaptiveQuiz.Api.Controllers;

[ApiController]
[Route("api/quiz")]
public class QuizController : ControllerBase
{
    private readonly QuizService _quizService;
    public QuizController(QuizService quizService)
    {
        _quizService = quizService;
    }

    [Authorize]
    [HttpPost("start")]
    public async Task<IActionResult> StartQuiz()
    {
        try
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

            if (string.IsNullOrEmpty(userEmail))
                return Unauthorized("User email not found in token");

            var attempt = await _quizService.StartQuizForUser(userEmail);

            return Ok(new
            {
                attempt.Id,
                attempt.StartingLevel
            });
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    [Authorize]
    [HttpGet("next")]
    public async Task<IActionResult> GetNext(int attemptId)
    {
        try
        {
            var userId = await GetCurrentUserId();
            var question = await _quizService.GetNextQuestion(attemptId, userId);
            var data = JsonSerializer.Deserialize<QuestionData>(question.Data);

            return Ok(new
            {
                question.Id,
                question.Text,
                question.Type,
                question.Difficulty,
                options = data?.Options
            });
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    [Authorize]
    [HttpPost("answer")]
    public async Task<IActionResult> SubmitAnswer([FromBody] SubmitAnswerRequest request)
    {
        try
        {
            var userId = await GetCurrentUserId();
            var result = await _quizService.SubmitAnswer(request, userId);
            return Ok(result);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    [Authorize]
    [HttpGet("results")]
    public async Task<IActionResult> GetResults(int attemptId)
    {
        try
        {
            var userId = await GetCurrentUserId();
            var result = await _quizService.GetResults(attemptId, userId);
            return Ok(result);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    [Authorize]
    [HttpGet("me")]
    public async Task<IActionResult> Me()
    {
        var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

        if (string.IsNullOrEmpty(userEmail))
            return Unauthorized("User email not found in token");

        var user = await _quizService.EnsureUserExists(userEmail);

        Console.WriteLine($"ROLE FROM DB: {user.Role}");
        Console.WriteLine($"EMAIL: {user.Email}");

        return Ok(new
        {
            user.Id,
            user.DisplayName,
            user.LastQuizAt,
            user.IsNameAutoGenerated,
            user.Role,

            canPlay = user.Role != Roles.User ||
                !user.LastQuizAt.HasValue ||
                user.LastQuizAt.Value.Month != DateTime.UtcNow.Month ||
                user.LastQuizAt.Value.Year != DateTime.UtcNow.Year,

            canManageQuestions = user.Role == Roles.Admin,
            canEnterLeaderboard = user.Role != Roles.Admin
        });
    }

    [Authorize]
    [HttpPut("display-name")]
    public async Task<IActionResult> UpdateDisplayName([FromBody] UpdateDisplayNameRequest request)
    {
        var userId = await GetCurrentUserId();
        var result = await _quizService.UpdateDisplayName(userId, request.DisplayName);

        return Ok(result);
    }

    [HttpGet("leaderboard")]
    public async Task<IActionResult> GetLeaderboard()
    {
        try
        {
            var result = await _quizService.GetLeaderboard();
            return Ok(result);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    [Authorize]
    [HttpGet("stats")]
    public async Task<IActionResult> GetStats()
    {
        try
        {
            var userId = await GetCurrentUserId();
            var result = await _quizService.GetUserStats(userId);
            return Ok(result);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    private async Task<int> GetCurrentUserId()
    {
        var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

        if (string.IsNullOrEmpty(userEmail))
            throw new Exception("User email not found in token");

        return await _quizService.GetUserIdFromEmail(userEmail);
    }
}