using AdaptiveQuiz.Api.Domain;
using AdaptiveQuiz.Api.DTOs.Requests;
using AdaptiveQuiz.Api.Exceptions;
using AdaptiveQuiz.Api.Infrastructure;
using AdaptiveQuiz.Api.DTOs.Responses;
using AdaptiveQuiz.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.Json;

namespace AdaptiveQuiz.Api.Controllers;

[ApiController]
[Route("api/quiz")]
public class QuizController : ControllerBase
{
    private readonly QuizService _quizService;
    private readonly UserService _userService;
    private readonly BugService _bugService;

    public QuizController(QuizService quizService, UserService userService, BugService bugService)
    {
        _quizService = quizService;
        _userService = userService;
        _bugService = bugService;
    }

    [Authorize]
    [HttpPost("start")]
    public async Task<IActionResult> StartQuizAsync()
    {
        var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

        if (string.IsNullOrEmpty(userEmail))
            return Unauthorized("User email not found in token");

        var attempt = await _quizService.StartQuizForUserAsync(userEmail);

		return Ok(new StartQuizResponse
		{
			Id = attempt.Id,
			StartingLevel = attempt.StartingLevel
		});
	}

    [Authorize]
    [HttpGet("next")]
    public async Task<IActionResult> GetNextAsync(int attemptId)
    {
        var userId = await GetCurrentUserId();

        var question = await _quizService.GetNextQuestionAsync(attemptId, userId);

        var data = JsonSerializer.Deserialize<QuestionData>(question.Data);

		return Ok(new NextQuestionResponse
		{
			Id = question.Id,
			Text = question.Text,
			Type = question.Type,
			Difficulty = question.Difficulty,
			Options = data?.Options ?? new List<string>()
		});
	}

    [Authorize]
    [HttpPost("answer")]
    public async Task<IActionResult> SubmitAnswerAsync([FromBody] SubmitAnswerRequest request)
    {
        var userId = await GetCurrentUserId();

        var result = await _quizService.SubmitAnswerAsync(request, userId);

        return Ok(result);
    }

    [Authorize]
    [HttpGet("results")]
    public async Task<IActionResult> GetResultsAsync(int attemptId)
    {
        var userId = await GetCurrentUserId();

        var result = await _quizService.GetResultsAsync(attemptId, userId);

        return Ok(result);
    }

    [Authorize]
    [HttpGet("me")]
    public async Task<IActionResult> MeAsync()
    {
        var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

        if (string.IsNullOrEmpty(userEmail))
            return Unauthorized("User email not found in token");

        var user = await _userService.GetOrCreateUserAsync(userEmail);

		return Ok(new CurrentUserResponse
		{
			Id = user.Id,
			DisplayName = user.DisplayName,
			LastQuizAt = user.LastQuizAt,
			IsNameAutoGenerated = user.IsNameAutoGenerated,
			Role = user.Role,
			CanPlay = _userService.CanPlay(user),
			CanManageQuestions = user.Role == Roles.Admin,
			CanEnterLeaderboard = user.Role != Roles.Admin
		});
	}

    [Authorize]
    [HttpPut("display-name")]
    public async Task<IActionResult> UpdateDisplayNameAsync([FromBody] UpdateDisplayNameRequest request)
    {
        var userId = await GetCurrentUserId();

        var result = await _userService.UpdateDisplayNameAsync(userId, request.DisplayName);

        return Ok(result);
    }

    [HttpGet("leaderboard")]
    public async Task<IActionResult> GetLeaderboardAsync()
    {
        var result = await _quizService.GetLeaderboardAsync();

        return Ok(result);
    }

    [Authorize]
    [HttpGet("stats")]
    public async Task<IActionResult> GetStatsAsync()
    {
        var userId = await GetCurrentUserId();

        var result = await _quizService.GetUserStatsAsync(userId);

        return Ok(result);
    }

    [Authorize]
    [HttpPost("bugs")]
    public async Task<IActionResult> CreateBugReportAsync([FromBody] CreateBugReportRequest request)
    {
        var userId = await GetCurrentUserId();

        var user = await _userService.GetUserAsync(userId);

        if (user.Role == Roles.Admin)
            return Forbid();

        var result = await _bugService.CreateBugReportAsync(userId, request);

        return Ok(result);
    }

    [Authorize]
    [HttpGet("bugs")]
    public async Task<IActionResult> GetMyBugReportsAsync()
    {
        var userId = await GetCurrentUserId();

        var result = await _bugService.GetUserBugReportsAsync(userId);

        return Ok(result);
    }

    [Authorize]
    [HttpGet("bugs/{id}")]
    public async Task<IActionResult> GetBugAsync(int id)
    {
        var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

        if (string.IsNullOrEmpty(userEmail))
            return Unauthorized();

        var user = await _userService.GetOrCreateUserAsync(userEmail);

        var bug = await _bugService.GetUserBugAsync(id, user.Id);

        if (bug == null)
            return Forbid();

        return Ok(bug);
    }

    [HttpGet("bugs/{id}/comments")]
    public async Task<IActionResult> GetBugCommentsAsync(int id)
    {
        var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

        if (string.IsNullOrEmpty(userEmail))
            return Unauthorized();

        var user = await _userService.GetOrCreateUserAsync(userEmail);

        var ownsBug = await _bugService.UserOwnsBugAsync(id, user.Id);

        if (!ownsBug)
            return Forbid();

        var comments = await _bugService.GetBugCommentsAsync(id);

        return Ok(comments);
    }

    [HttpPost("bugs/{id}/comments")]
    public async Task<IActionResult> AddBugCommentAsync(int id, [FromBody] CreateBugCommentRequest request)
    {
        var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

        if (string.IsNullOrEmpty(userEmail))
            return Unauthorized();

        var user = await _userService.GetOrCreateUserAsync(userEmail);

        var ownsBug = await _bugService.UserOwnsBugAsync(id, user.Id);

        if (!ownsBug)
            return Forbid();

            var comment = await _bugService.AddBugCommentAsync(id, user.Id, request);

            return Ok(new BugCommentResponse
            {
                Id = comment.Id,
                Comment = comment.Comment,
                CreatedAt = comment.CreatedAt,
                DisplayName = user.DisplayName,
                Role = user.Role
            });
    }

    private async Task<int> GetCurrentUserId()
    {
        var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;

        if (string.IsNullOrEmpty(userEmail))
            throw new UserNotAuthenticatedException();

        return await _userService.GetUserIdFromEmailAsync(userEmail);
    }
}