using Microsoft.EntityFrameworkCore;

namespace AdaptiveQuiz.Api.Domain;

[Index(nameof(Email), IsUnique = true)]
public class User
{
    public int Id { get; set; }
    public string Email { get; set; } = "";
    public string Role { get; set; } = "User";
    public string DisplayName { get; set; } = "";
    public int CurrentLevel { get; set; } = 1;
    public DateTime? LastQuizAt { get; set; }
    public bool IsNameAutoGenerated { get; set; } = true;
}
