using AdaptiveQuiz.Api.Domain;
using AdaptiveQuiz.Api.Exceptions;
using AdaptiveQuiz.Api.Infrastructure;
using AdaptiveQuiz.Api.Services;
using AdaptiveQuiz.Api.Tests.TestHelpers;
using FluentAssertions;

namespace AdaptiveQuiz.Api.Tests.Services;

public class QuizServiceStartQuizTests
{
    [Fact]
    public async Task StartQuizForUserAsync_ShouldCreateNewQuizAttempt()
    {
        // Arrange
        var context = TestDbContextFactory.Create();

        var userService = new UserService(context);
        var quizService = new QuizService(context, userService);

        var email = "geoff@test.com";

        // Act
        var attempt = await quizService.StartQuizForUserAsync(email);

        // Assert
        attempt.Should().NotBeNull();
        attempt.Score.Should().Be(0);
        attempt.StartingLevel.Should().Be(1);
        attempt.CurrentLevel.Should().Be(1);

        var user = await userService.GetOrCreateUserAsync(email);

        user.LastQuizAt.Should().NotBeNull();

        context.QuizAttempts.Should().ContainSingle();
        context.Users.Should().ContainSingle();
    }

    [Fact]
    public async Task StartQuizForUserAsync_ShouldThrow_WhenUserAlreadyPlayedThisMonth()
    {
        // Arrange
        var context = TestDbContextFactory.Create();

        var user = new User
        {
            Email = "geoff@test.com",
            Role = Roles.User,
            CurrentLevel = 1,
            DisplayName = "Geoff",
            IsNameAutoGenerated = false,
            LastQuizAt = DateTime.UtcNow
        };

        context.Users.Add(user);
        await context.SaveChangesAsync();

        var userService = new UserService(context);
        var quizService = new QuizService(context, userService);

        // Act
        Func<Task> act = async () =>
            await quizService.StartQuizForUserAsync(user.Email);

        // Assert
        await act.Should()
            .ThrowAsync<QuizAlreadyTakenException>();
    }

    [Fact]
    public async Task StartQuizForUserAsync_ShouldAllowAdminToStartMultipleQuizzesInSameMonth()
    {
        // Arrange
        var context = TestDbContextFactory.Create();

        var user = new User
        {
            Email = "admin@test.com",
            Role = Roles.Admin,
            CurrentLevel = 5,
            DisplayName = "Admin",
            IsNameAutoGenerated = false,
            LastQuizAt = DateTime.UtcNow
        };

        context.Users.Add(user);
        await context.SaveChangesAsync();

        var userService = new UserService(context);
        var quizService = new QuizService(context, userService);

        // Act
        var attempt = await quizService.StartQuizForUserAsync(user.Email);

        // Assert
        attempt.Should().NotBeNull();
        attempt.UserId.Should().Be(user.Id);
        attempt.Score.Should().Be(0);
        attempt.StartingLevel.Should().Be(5);
        attempt.CurrentLevel.Should().Be(5);

        context.QuizAttempts.Should().ContainSingle();
    }
}