using AdaptiveQuiz.Api.Domain;
using AdaptiveQuiz.Api.DTOs.Requests;
using AdaptiveQuiz.Api.Exceptions;
using AdaptiveQuiz.Api.Infrastructure;
using AdaptiveQuiz.Api.Services;
using AdaptiveQuiz.Api.Tests.TestHelpers;
using FluentAssertions;

namespace AdaptiveQuiz.Api.Tests.Services
{
    public class UserServiceTests
    {

        [Fact]
        public async Task GetOrCreateUserAsync_ShouldCreateUser_WhenUserDoesNotExist()
        {
            // Arrange
            var context = TestDbContextFactory.Create();
            var userService = new UserService(context);

            // Act
            var user = await userService.GetOrCreateUserAsync("geoff@test.com");

            // Assert
            user.Should().NotBeNull();
            user.Email.Should().Be("geoff@test.com");
            user.Role.Should().Be(Roles.User);
            user.CurrentLevel.Should().Be(1);
            user.IsNameAutoGenerated.Should().BeTrue();

            context.Users.Should().ContainSingle();
        }

        [Fact]
        public async Task GetOrCreateUserAsync_ShouldReturnExistingUser_WhenUserAlreadyExists()
        {
            // Arrange
            var context = TestDbContextFactory.Create();

            var existingUser = new User
            {
                Email = "geoff@test.com",
                DisplayName = "Geoff",
                Role = Roles.User,
                CurrentLevel = 5
            };

            context.Users.Add(existingUser);
            await context.SaveChangesAsync();

            var userService = new UserService(context);

            // Act
            var user = await userService.GetOrCreateUserAsync(existingUser.Email);

            // Assert
            user.Id.Should().Be(existingUser.Id);
            user.CurrentLevel.Should().Be(5);

            context.Users.Should().ContainSingle();
        }

        [Fact]
        public async Task UpdateDisplayNameAsync_ShouldUpdateDisplayName()
        {
            // Arrange
            var context = TestDbContextFactory.Create();

            var user = new User
            {
                Email = "geoff@test.com",
                DisplayName = "OldName",
                IsNameAutoGenerated = true
            };

            context.Users.Add(user);
            await context.SaveChangesAsync();

            var userService = new UserService(context);

            // Act
            var result = await userService.UpdateDisplayNameAsync(user.Id, "NewName");

            // Assert
            result.DisplayName.Should().Be("NewName");

            var savedUser = await context.Users.FindAsync(user.Id);

            savedUser!.DisplayName.Should().Be("NewName");
            savedUser.IsNameAutoGenerated.Should().BeFalse();
        }

        [Fact]
        public async Task UpdateDisplayNameAsync_ShouldThrow_WhenDisplayNameIsTooShort()
        {
            // Arrange
            var context = TestDbContextFactory.Create();

            var user = new User
            {
                Email = "geoff@test.com"
            };

            context.Users.Add(user);
            await context.SaveChangesAsync();

            var userService = new UserService(context);

            // Act
            Func<Task> act = () =>
                userService.UpdateDisplayNameAsync(user.Id, "ab");

            // Assert
            await act.Should()
                .ThrowAsync<InvalidDisplayNameException>();
        }

        [Fact]
        public void CanPlay_ShouldReturnFalse_WhenUserHasAlreadyPlayedThisMonth()
        {
            // Arrange
            var context = TestDbContextFactory.Create();

            var userService = new UserService(context);

            var user = new User
            {
                Role = Roles.User,
                LastQuizAt = DateTime.UtcNow
            };

            // Act
            var canPlay = userService.CanPlay(user);

            // Assert
            canPlay.Should().BeFalse();
        }

    }
}
